# Deployment da Aplicação Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:        
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: rfpereira/conversaotemperatura:v1
          ports:
            - containerPort: 8080

---
# Service da Applicação Web
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30000
  type: NodePort